# Generated by Django 3.1 on 2020-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_text', models.CharField(max_length=10000)),
                ('post_image', models.ImageField(upload_to='post_images/')),
            ],
        ),
    ]
